modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="survival_of_the_minecraftist"
version="1.0.0"
displayName="Survival of the Minecraftist"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="souls, MCreator"

[[dependencies.survival_of_the_minecraftist]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




